### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by luofei614** [zake7749/Chatbot#25]
FileNotFoundError: [Errno 2] No such file or directory: 'model/ch-corpus-3sg.bin'

**Comment by zake7749** [comment]
您好，

這個錯誤應該是沒有載入或沒有抓到詞向量模型 ( 預設檔名為 `ch-corpus-3sg.bin` ) 所導致的，
目前可以從[chatbot.py#39](https://github.com/zake7749/Chatbot/blob/master/Chatbot/chatbot.py#L39)設定詞向量模型的位置。

我近期會將這個參數追加到 `Chatbot`的建構子中，並把部分冗餘的內容清除掉，感謝您的告知。

**Comment by luofei614** [comment]
您好， 
向量模型我已经手动加入了。  
Chatbot/Chatbot/QuestionAnswering/data/processed/reply  这个目录的文件也没有。   

另外 我改了一行代码才运行正常。   rulebase.py 中
self.model = models.KeyedVectors.load_word2vec_format(path,binary=True)
改为了
self.model = models.KeyedVectors.load(path)

不知道为什么用load_word2vec_format会报unicode编码的错误

**Comment by zake7749** [comment]
reply 的文件是給問答模組使用的，可以參考[問答測試用資料集](https://github.com/zake7749/Chatbot#%E5%95%8F%E7%AD%94%E6%B8%AC%E8%A9%A6%E7%94%A8%E8%B3%87%E6%96%99%E9%9B%86) 來下載測試資料集並配置。
不過因為搜尋方式用的是 BM25，可能要先將資料集轉換為簡體文本，文字比對才會有效。

而關於模型載入的錯誤，
我推測是因為最近 gensim 對詞向量模組的更新所致,
為了兼用性,我以前在教學文件中訓練出的模型是 binary file,
不過新版 gensim 載入 bin 模型時似乎會碰到一些狀況,
所以後來教學就改用新版的儲存方式(save()),
應該是模型當初的儲存方式不同才會報錯。

**Comment by magcle** [comment]
我现在也是  ch-corpus-3sg.bin 没找到， 这个文件怎么获取的啊~~

**Comment by david30907d** [comment]
@lener1987  word2vec的模型需要自己先訓練喔
因為模型容量太大所以不會放上github
你可以參考 @zake7749 大大的教學文
http://zake7749.github.io/2016/08/28/word2vec-with-gensim/

**Comment by zake7749** [comment]
是的，感謝 david 幫忙回覆，
請先依自己的需求進行詞嵌入的訓練，
並調整 path 告知 chatbot 模型所在的位置。

```
import Chatbot.chatbot as chatbot

bot = chatbot.Chatbot(w2v_model_path='your_model')
```

**Comment by ARJhe** [comment]
Reference
--
