### ISSUE TITLE
对话意图抽取

### ISSUE THREAD

**Issue by well707** [zake7749/Chatbot#28]
您好，请问对话意图抽取这块是如何实现的，有详细的资料讲解么，对这块比较感兴趣，想深入了解下。

**Comment by zake7749** [comment]
您好，

這個專案使用的其實都是相當樸素的方法，
於意圖抽取上，我對每個主題定義了關鍵字與子主題，比如說：
```json
    {
        "domain": "購買",
        "response": [
        	"正在將您導向購物模組"
        ],
        "concepts": [
            "購買","購物","訂購"
        ],
        "children": [
            "購買生活用品",
            "購買家電",
            "購買食物",
        ]
    }
```
這些模板能夠構成出一個圖狀節構，意圖抽取可以視為對這張圖的走訪過程。

系統的運作流程能這麼考慮：
```
1. 讀入使用者輸入
2. 將使用者輸入與各個意圖計算分數，取其中得分最高者做為主要意圖
3. 檢查該主要意圖是不是還有子意圖集
    3-1 若無子意圖集，完成意圖抽取，返回意圖走訪路徑
    3-2 若尚有子意圖集，回到步驟 2 ，將各個意圖考慮為子意圖集
```
計算得分的方式是預先對一個意圖定義好若干個關鍵字(模板中的 `concepts`)，
對使用者輸入進行斷詞後，再和該意圖所有的關鍵詞計算相似分數，
最後採用得分最高者做為這句話對該主題的分數。

**Comment by well707** [comment]
了解了，谢谢您的解答。

**Comment by well707** [comment]
我们也是首先人工分类，对每一类罗列了很多属于该类别的词语。我们首先利用规则分类，规则无法处理的则抽取问题的关键词，然后利用词向量方法计算关键词与各个类别词语（不过我们处理的比较粗矿，我们把每一类的关键词的向量加起来）的相似度，取相似度高的。

**Comment by tielei** [comment]
請問 RuleMatcher/rule/ 下面的這些json文件，是靠人工建立起來的嗎？

**Comment by zake7749** [comment]
是的，內部規則是人工設計的。

**Comment by tielei** [comment]
@zake7749 非常感謝回復！

**Comment by gina83221** [comment]
你好 
想要請問每個主題的關鍵字與子主題是如何定義的?
謝謝~
