### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ggzhang0071** [zake7749/Chatbot#30]
File "test.py", line 9, in main
    model = models.Word2Vec.load_word2vec_format('ch-corpus-3sg.bin',binary=True)

gensim/models/word2vec.py", line 1608, in load_word2vec_format
    raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.")

**Comment by shingsoso** [comment]
Are you using Python 3.5 ?

**Comment by zake7749** [comment]
Sorry for the delayed response.

The method `load_word2vec_format` is deprecated in current gensim, so you can fix it by replacing the deprecated one with `models.Word2Vec.load('your_w2v_model_path')`.

I will also fix this problem soon,  thank you for your feedback. 👍
