### ISSUE TITLE
關於demo.py, test.py執行之詢問

### ISSUE THREAD

**Issue by Xenorock** [zake7749/Chatbot#33]
您好 感謝提供這個資源讓我們可以使用
如同題目 我在運行demo.py時遇到了問題(下附錯誤敘述)
我參照了其他使用者所提問過的
得知word2vec的model需要進行訓練
於是參考了您的另一篇文章成功訓練完成
測試demo.py  (word2vec的 非本chatbot之demo.py)  也運行無誤
然而我將該model代回chatbot時
將demo.py, demo_chatbot.py 等等需要撰寫model路徑的檔案都改變後
卻仍舊出現錯誤訊息
希望po主能幫我解答 感激不盡

https://images.plurk.com/3eU8qiGvmUsxseftD1eQ.jpg

**Comment by zake7749** [comment]
您好，這是詞向量本身造成的錯誤，

您在圖中執行的檔案看起來是 [test.py](https://github.com/zake7749/Chatbot/blob/master/Chatbot/model/test.py)，而非[Chatbot/demo.py](https://github.com/zake7749/Chatbot/blob/master/demo.py)。test.py 與 word2vec-tutorial 中的 [demo.py](https://github.com/zake7749/word2vec-tutorial/blob/master/demo.py) 除了載入路徑外，其他程式碼是完全相同的，理論上不會發生不一致的行為。請先檢查看看，您放在 test.py 中的詞向量 `model.bin`，是否跟 word2vec-tutorial/demo.py 中使用的詞向量是同一個檔案。
