### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by o55665516** [zake7749/Chatbot#35]
我利用您提供的"使用 gensim 訓練中文詞向量"訓練好後，把模型放在該資料夾
也有將console更改如下
c = console.Console(model_path='word2vec-tutorial-master/word2vec.model')
但是出現[Errno 2] No such file or directory: 'word2vec-tutorial-master/word2vec.model'
請問我哪邊沒有完成嗎~~!?

**Comment by zake7749** [comment]
這個錯誤是找不到模型所致，請確認相對路徑是否正確。

**Comment by o55665516** [comment]
我路徑有稍作修改
變成出現以下挫，請問大大這是什麼原因~~
[Gensim] 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
