### ISSUE TITLE
問答測試用資料集檔案遺失

### ISSUE THREAD

**Issue by xandyxor** [zake7749/Chatbot#39]
您好
下載連結
https://drive.google.com/file/d/0BxfXm7KkNKc-RkY2Z1pONUlqODg/view?usp=sharing
出現
抱歉，您要求的檔案不存在。
請確定網址無誤，且檔案確實存在。
請問能否重新上傳

**Comment by zake7749** [comment]
您好，檔案已重新上傳。

**Comment by xandyxor** [comment]
感謝您 ＾＿＾
