### ISSUE TITLE
model

### ISSUE THREAD

**Issue by gdjssfxy302** [zake7749/Chatbot#40]
No such file or directory: 'model/ch-corpus-3sg.bin,请问如何获取这个模型的？

**Comment by zake7749** [comment]
這是一個簡易的詞向量模型，請參考 [word2vec-tutorial](https://github.com/zake7749/word2vec-tutorial) 進行訓練。

**Comment by gdjssfxy302** [comment]
在维基百科官网上下载bz2后缀的语料库通过winRAR解压后得到的txt文件是空的，显示0个字节，请问这是怎么回事的？

**Comment by gdjssfxy302** [comment]
> 這是一個簡易的詞向量模型，請參考 word2vec-tutorial 進行訓練。

谢谢你的回答！我试一下

**Comment by gdjssfxy302** [comment]
> 這是一個簡易的詞向量模型，請參考 word2vec-tutorial 進行訓練。

@zake7749 谢谢你的回答！
