### ISSUE TITLE
使用QA模組遇到問題

### ISSUE THREAD

**Issue by fukismall** [zake7749/Chatbot#41]
感謝您提供code讓大家參考
我有先依照問答測試用資料集進行配置
但在執行demo_qa.py遇到問題不知道怎麼解決，如圖
https://i.imgur.com/drsgZIp.jpg
希望大大能幫我解答

**Comment by zake7749** [comment]
這個錯誤是由於未安裝 [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) 所導致，請執行 `pip install fuzzywuzzy` 以配置好環境。
