### ISSUE TITLE
问答测试用资料集缺失

### ISSUE THREAD

**Issue by gdjssfxy302** [zake7749/Chatbot#44]
题主大大，您好！
这个链接https://drive.google.com/file/d/11JlbmYmuu00TfmfdAfyoGK_E3VMp8Vd_/view出现访问页面不存在，请问能否重新上传一份问答测试用资料集？或者发我一份新的下载链接？谢谢！

**Comment by zake7749** [comment]
檔案是存在的，只是因為我是放在 Google Drive，您可能需要透過 VPN 取得。

**Comment by gdjssfxy302** [comment]
@zake7749 题主大大，我这里访问不了Google Drive，这是我的一个毕业设计项目，现在快完成了，可以发我一个能够访问的百度云链接吗？我需要取得这个问答测试用资料集，非常感谢了！

**Comment by zake7749** [comment]
請[點此](https://github.com/zake7749/Gossiping-Chinese-Corpus/raw/master/data/source_replies/reply.7z)下載。

**Comment by gdjssfxy302** [comment]
@zake7749 下载好了，非常感谢题主的分享！

**Comment by gdjssfxy302** [comment]
@zake7749 题主大大，我通过您下载好的问答测试资料集跑了一下，发现呈现出来的问答模式效果不是很好，对问题的回复都是一些答非所问，还有就是对同一个词语的匹配回应都不太一样，比如说“下雨”，这是什么问题的？如何解决呢？现在我把呈现出来的问答模式赋于如下：
下雨
對啊 可能會有肥宅接近你
明天会下雨吗
Handler of '住宿' have not implemented
None
明天会下雨吗
Handler of '住宿' have not implemented
None
明天会下雨吗
Handler of '住宿' have not implemented
None
下雨
便利商店買60元一把 很難嗎?!
天气下雨吗
出門帶傘是常識，連這個都不知道？怎麼長大的？
天气下雨
都來八卦板討拍了 還魯宅不說勒 呵
