### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by kelvinng2017** [zake7749/Chatbot#47]
大神你我因功課需要，需要製作聊天機器人
![image](https://user-images.githubusercontent.com/24961569/60955035-9da46600-a332-11e9-808f-1e5604f853c5.png)
但是我無法執行這個專案

**Comment by zake7749** [comment]
請確認是否有正確安裝 [scipy](https://github.com/scipy/scipy)。

**Comment by kelvinng2017** [comment]
請問是要用pip 還是conda 安裝，版本有影響？

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Justin Yang <notifications@github.com> 于2019年7月10日周三 下午8:17写道：

**Comment by zake7749** [comment]
都可以，我比較建議使用 conda 安裝。

**Comment by kelvinng2017** [comment]
我試看

Justin Yang <notifications@github.com> 於 2019年7月11日 週四 19:28 寫道：

**Comment by kelvinng2017** [comment]
![image](https://user-images.githubusercontent.com/24961569/61267063-d5932980-a7c8-11e9-98bb-15bd5f26d867.png)
大神QA模式這樣正常嗎，我執行ddemo_qa.py 
還有一定要有w2v_model才能執行chatbot.py嗎

**Comment by kelvinng2017** [comment]
![image](https://user-images.githubusercontent.com/24961569/61268681-c1eac180-a7ce-11e9-9437-e5b8ac32301b.png)
大神不好意思又來煩你，請問上圖的的json檔案VOTE,content是什麼意思
demo_qa.py是以什麼方式進行執行，例如我輸入"笑話"，讓後機器人就回复我"廢到笑不出來"

**Comment by zake7749** [comment]
從第一張圖來看，demo_qa 的運作是正常的。
QA 模組的設計是基於搜索，
它會比對使用者輸入跟語料庫中所有的文章標題，
找出最相似的文章後，再 sample 其他 users 對該文章的推文作為回覆。

> 還有一定要有w2v_model才能執行chatbot.py嗎

預設是如此。關於 w2v_model 的用途，可參考 #31 
如果您沒有這些需求的話，可以用 demo_qa 的方式執行這個專案。

第二張圖的 User / Vote 和本專案沒有直接關係，具體細節請參見 [PTT-Crawler](https://github.com/zake7749/PTT-Crawler)。

**Comment by kelvinng2017** [comment]
謝謝

Justin Yang <notifications@github.com> 於 2019年7月16日 週二 16:39 寫道：

**Comment by kelvinng2017** [comment]
![image](https://user-images.githubusercontent.com/24961569/61350956-dba60a80-a89b-11e9-923d-75a3b5490c25.png)
大神請問請問上圖的JSON格式能應用在QA模式嗎

**Comment by zake7749** [comment]
不行，要先按[實驗簡述](https://github.com/zake7749/PTT-Chat-Generator)進行前處理。

不過，如果您打算自己實作匹配算法，只是想取得處理後的問答對做為語料的話，可以直接用 [Gossiping-Chinese-Corpus](https://github.com/zake7749/Gossiping-Chinese-Corpus)。
