### ISSUE TITLE
Rulebase生成

### ISSUE THREAD

**Issue by quab-087** [zake7749/Chatbot#48]
您好，想請教專案中的rulebase是如何生成的呢?

**Comment by zake7749** [comment]
您好，
rulebase 中現有 rules 大部分是由人工標註而來的。

**Comment by quab-087** [comment]
> 您好，
> rulebase 中現有 rules 大部分是由人工標註而來的。

我的想法是透過訓練好的模型，兩個詞之間如果有很高的相似度，那基本可以歸為同一種domain下的概念，但children無法用這種方式去自動生成，例如：
`
{
    "concept": "購買",
    "children": [
        "購買物品"
    ]
}
`
購買與物品之間相關性可能不高，請問有什麼方法能夠判斷是否適合當作children嗎?

**Comment by zake7749** [comment]
基於無監督的方式自動生成 children 並不容易，因為 children 的定義需要隨著應用類型動態地調整。
比如說對於購買這個 parent node 而言，
如果您的應用端是個保險銷售系統，那購買的 children 可能會是買保單、買壽險，
但如果應用端換成了一個食物外送平台，那購買的 children 則可能是買麵、買飯或買湯，
當然這種定義方式存在著一個假設：使用者不會請保險推銷員買飯、或者不會跟外送平台買保險。

為了處理假設外的情形，這個專案是結合了 chit-chat ，將不合應用端任務的對話導向一個閒聊機器人。
如果您想完全跳脫這個假設，即是做一個通用型規則分類器的話，
在受詞的處理可套用廣義知網的架構，不過對於採取的動作（如購買）您仍須自行引入應用端的資訊。

**Comment by quab-087** [comment]
了解了，感謝您的回覆~
I will close this issue.
